admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('provasOrais.urls')),
    path('admin/', admin.site.urls),
]

provasOrais/urls.py
from django.urls import path
from provasOrais import views

app_name = 'provas'
urlpatterns = [
    path('', views.home, name='home'),

    path('usuario/novo', views.cadastrarUsuario, name='cadastrarUsuario'),

    path('alunos/', views.alunos, name='alunos'),
    path('alunos/<int:id>/', views.aluno, name='aluno'),
    path('alunos/novo/', views.cadastrarAluno, name='cadastrarAluno'),
    path('alunos/<int:id>/atualizar', views.atualizarAluno, name='atualizarAluno'),
    path('alunos/<int:id>/apagar', views.apagarAluno, name='apagarAluno'),
    
    path('assuntos/', views.assuntos, name='assuntos'),
    path('assuntos/<int:id>/', views.assunto, name='assunto'),
    path('assuntos/novo/', views.cadastrarAssunto, name='cadastrarAssunto'),
    path('assuntos/<int:id>/atualizar', views.atualizarAssunto, name='atualizarAssunto'),
    path('assuntos/<int:id>/apagar', views.apagarAssunto, name='apagarAssunto'),
    
    path('disciplinas/', views.disciplinas, name='disciplinas'),
    path('disciplinas/<int:id>/', views.disciplina, name='disciplina'),
    path('disciplinas/novo/', views.cadastrarDisciplina, name='cadastrarDisciplina'),
    path('disciplinas/<int:id>/atualizar', views.atualizarDisciplina, name='atualizarDisciplina'),
    path('disciplinas/<int:id>/apagar', views.apagarDisciplina, name='apagarDisciplina'),
    
    path('perguntas/', views.perguntas, name='perguntas'),
    path('perguntas/<int:id>/', views.pergunta, name='pergunta'),
    path('perguntas/novo/', views.cadastrarPergunta, name='cadastrarPergunta'),
    path('perguntas/assunto/', views.receberAssunto, name='receberAssunto'),
    path('perguntas/<int:id>/atualizar', views.atualizarPergunta, name='atualizarPergunta'),
    path('perguntas/<int:id>/apagar', views.apagarPergunta, name='apagarPergunta'),
    
    path('questoes/', views.questoes, name='questoes'),
    path('questoes/<int:id>/', views.questao, name='questao'),
    path('questoes/novo/', views.cadastrarQuestao, name='cadastrarQuestao'),
    path('questoes/<int:id>/atualizar', views.atualizarQuestao, name='atualizarQuestao'),
    path('questoes/<int:id>/apagar', views.apagarQuestao, name='apagarQuestao'),
    
    path('turmas/', views.turmas, name='turmas'),
    path('turmas/<int:id>/', views.turma, name='turma'),
    path('turmas/novo/', views.cadastrarTurma, name='cadastrarTurma'),
    path('turmas/<int:id>/atualizar', views.atualizarTurma, name='atualizarTurma'),
    path('turmas/<int:id>/apagar', views.apagarTurma, name='apagarTurma'),

    path('provas/', views.provas, name='provas'),
    path('provas/<int:id>/', views.prova, name='prova'),
    path('provas/novo/pre/', views.dadosProva, name='dadosProva'),
    path('provas/novo/', views.cadastrarProva, name='cadastrarProva'),
    path('provas/<int:id>/atualizar', views.atualizarProva, name='atualizarProva'),
    path('provas/<int:id>/apagar', views.apagarProva, name='apagarProva'),
]

provasOrais/models.py
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User


# Create your models here.
class Disciplina(models.Model):
    class Meta:
        verbose_name = 'Disciplina'
        verbose_name_plural = 'Disciplinas'
    
    disciplina = models.CharField(max_length=255)
    created_date = models.DateTimeField(default=timezone.now)
    ativo = models.BooleanField(default=True)
    # owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self) -> str:
        return self.disciplina


class Assunto(models.Model):
    class Meta:
        verbose_name = 'Assunto'
        verbose_name_plural = 'Assuntos'
    
    assunto = models.CharField(max_length=255)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.DO_NOTHING)
    created_date = models.DateTimeField(default=timezone.now)
    ativo = models.BooleanField(default=True)
    # owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self) -> str:
        return self.assunto


class Turma(models.Model):
    class Meta:
        verbose_name = 'Turma'
        verbose_name_plural = 'Turmas'
    
    Turnos = models.TextChoices('Turnos', 'Diurno Matutino Vespertino Noturno')

    numero = models.CharField(max_length=255)
    turno = models.CharField(choices=Turnos, default='Diurno', max_length=255)
    ano = models.CharField(max_length=4)
    created_date = models.DateTimeField(default=timezone.now)
    ativo = models.BooleanField(default=True)
    # owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True)
    
    def __str__(self) -> str:
        return self.numero


class Questao(models.Model):
    class Meta:
        verbose_name = 'Questão'
        verbose_name_plural = 'Questões'

    questao = models.TextField()
    assunto = models.ForeignKey(Assunto, on_delete=models.DO_NOTHING)
    created_date = models.DateTimeField(default=timezone.now)
    ativo = models.BooleanField(default=True)
    # owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self) -> str:
        return self.questao


class Aluno(models.Model):
    class Meta:
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'

    nome = models.CharField(max_length=255)
    turma = models.ForeignKey(Turma, on_delete=models.DO_NOTHING)
    created_date = models.DateTimeField(default=timezone.now)
    ativo = models.BooleanField(default=True)
    # owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self) -> str:
        return self.nome


class Prova(models.Model):
    class Meta:
        verbose_name = 'Prova'
        verbose_name_plural = 'Provas'

    aluno = models.ForeignKey(Aluno, on_delete=models.DO_NOTHING)
    nota = models.FloatField(max_length=10, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    ativo = models.BooleanField(default=True)


class Pergunta(models.Model):
    class Meta:
        verbose_name = 'Pergunta'
        verbose_name_plural = 'Perguntas'

    prova = models.ForeignKey(Prova, on_delete=models.DO_NOTHING)
    questao = models.ForeignKey(Questao, on_delete=models.DO_NOTHING)
    resposta = models.TextField(blank=True)
    nota = models.FloatField(max_length=10, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    ativo = models.BooleanField(default=True)
    # owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self) -> str:
        return f'{self.questao}:\n{self.resposta}'

provasOrais/forms.py
from django import forms
from provasOrais.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError


class UsuarioForm(UserCreationForm):
    first_name = forms.CharField(
        required = True,
    )
    last_name = forms.CharField(
        required = True,
    )
    email = forms.EmailField(
        required = True,
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe email com esse nome', code='invalid')
            )
        
        return email


class AlunoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs.update({
            'placeholder': 'Insira seu nome...',
        })

    class Meta:
        model = Aluno
        fields = ('nome', 'turma')


class AssuntoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    class Meta:
        model = Assunto
        fields = ('assunto', 'disciplina')


class DisciplinaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Disciplina
        fields = ("disciplina",)


class TurmaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    class Meta:
        model = Turma
        fields = ('numero', 'turno', 'ano')


class QuestaoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Questao
        fields = ('questao', 'assunto')


class nonModelProvaForm(forms.Form):
    aluno = forms.ModelChoiceField(Aluno.objects.filter(ativo=True))
    assunto = forms.ModelChoiceField(Assunto.objects.filter(ativo=True))


class ProvaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Prova
        fields = ('aluno', 'nota')


class AssuntoPerguntaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    class Meta:
        model = Questao
        fields = ('assunto',)


class PerguntaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    class Meta:
        model = Pergunta
        fields = ('questao', 'resposta', 'nota')


class AtualizarPerguntaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Pergunta
        fields = ('resposta', 'nota')

provasOrais/views/alunos.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpRequest
from provasOrais.models import Aluno
from provasOrais.forms import AlunoForm


BASE_PATH = 'provasOrais/templates/'
# Create your views here.
def alunos(request: HttpRequest):
    novo = reverse('provas:cadastrarAluno')
    listarAlunos = Aluno.objects.all().filter(ativo=True)
    context={
        'alunos': listarAlunos,
        'novo': novo,
        }
    return render(request, f'{BASE_PATH}listarAlunos.html', context=context)

def aluno(request: HttpRequest, id):
    aluno = get_object_or_404(Aluno, id=id, ativo=True)
    atualizar = reverse('provas:atualizarAluno', args=(id,))
    apagar = reverse('provas:apagarAluno', args=(id,))
    context={
        'listar': {
            'url': reverse('provas:alunos'),
            'nome': 'Alunos',
        },
        'aluno': aluno,
        'atualizar': atualizar,
        'apagar': apagar,
    }
    return render(request, f'{BASE_PATH}consultarAluno.html', context=context)

def cadastrarAluno(request: HttpRequest):
    form_action = reverse('provas:cadastrarAluno')
    if request.method == "POST":
        form = AlunoForm(request.POST)
        context={
            'listar': {
                'url': reverse('provas:alunos'),
                'nome': 'Alunos',
            },
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid:
            aluno = form.save()
            messages.success(request, f'Aluno {aluno.nome} cadastrado com sucesso!')
            return redirect("provas:cadastrarAluno")

        return render(request, f'{BASE_PATH}cadastrarAluno.html', context=context)    
    context={
        'listar': {
            'url': reverse('provas:alunos'),
            'nome': 'Alunos',
        },
        'form': AlunoForm(),
        'form_action': form_action,
    }
    return render(request, f'{BASE_PATH}cadastrarAluno.html', context=context)

def atualizarAluno(request: HttpRequest, id):
    aluno = get_object_or_404(Aluno, id=id, ativo=True)
    form_action = reverse('provas:atualizarAluno', args=(id,))
    if request.method == "POST":
        form = AlunoForm(request.POST, instance=aluno)
        context={
            'listar': {
                'url': reverse('provas:alunos'),
                'nome': 'Alunos',
            },
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid:
            aluno = form.save()
            messages.success(request, f'Aluno {aluno.nome} atualizado com sucesso!')
            return redirect("provas:atualizarAluno", id=aluno.id)

        return render(request, f'{BASE_PATH}cadastrarAluno.html', context=context)
    context={
        'listar': {
            'url': reverse('provas:alunos'),
            'nome': 'Alunos',
        },
        'form': AlunoForm(instance=aluno),
        'form_action': form_action,
    }
    return render(request, f'{BASE_PATH}cadastrarAluno.html', context=context)

def apagarAluno(request: HttpRequest, id):
    aluno = get_object_or_404(Aluno, id=id, ativo=True)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        aluno.delete()
        return redirect('provas:alunos')

    context={
        'listar': {
            'url': reverse('provas:alunos'),
            'nome': 'Alunos',
        },
        'aluno': aluno,
        'confirmation': confirmation,
    }
    return render(request, f'{BASE_PATH}consultarAluno.html', context=context)

provasOrais/views/assuntos.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpRequest
from provasOrais.models import Assunto
from provasOrais.forms import AssuntoForm

BASE_PATH = 'provasOrais/templates/'
# Create your views here.
def assuntos(request):
    listarAssuntos = Assunto.objects.all().filter(ativo=True)
    novo = reverse('provas:cadastrarAssunto')
    context={
        'assuntos': listarAssuntos,
        'novo': novo,
    }
    return render(request, f'{BASE_PATH}listarAssuntos.html', context=context)

def assunto(request, id):
    assunto = Assunto.objects.get(id=id)
    atualizar = reverse('provas:atualizarAssunto', args=(id,))
    apagar = reverse('provas:apagarAssunto', args=(id,))
    context={
        'listar': {
            'url': reverse('provas:assuntos'),
            'nome': 'Assuntos',
        },
        'assunto': assunto,
        'atualizar': atualizar,
        'apagar': apagar,
    }
    return render(request, f'{BASE_PATH}consultarAssunto.html', context=context)

def cadastrarAssunto(request: HttpRequest):
    form_action = reverse('provas:cadastrarAssunto')
    if request.method == "POST":
        form = AssuntoForm(request.POST)
        context={
            'listar': {
                'url': reverse('provas:assuntos'),
                'nome': 'Assuntos',
            },
            'form': form,
            'form': form_action,
        }

        if form.is_valid:
            assunto = form.save()
            messages.success(request, f'Assunto {assunto.assunto} cadastrado com sucesso!')
            return redirect("provas:cadastrarAssunto")

        return render(request, f'{BASE_PATH}cadastrarAssunto.html', context=context)    
    context={
        'listar': {
            'url': reverse('provas:assuntos'),
            'nome': 'Assuntos',
        },
        'form': AssuntoForm(),
        'from_action': form_action,
    }
    return render(request, f'{BASE_PATH}cadastrarAssunto.html', context=context)

def atualizarAssunto(request: HttpRequest, id):
    assunto = get_object_or_404(Assunto, id=id, ativo=True)
    form_action = reverse('provas:atualizarAssunto', args=(id,))
    if request.method == "POST":
        form = AssuntoForm(request.POST, instance=assunto)
        context={
            'listar': {
                'url': reverse('provas:assuntos'),
                'nome': 'Assuntos',
            },
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid:
            assunto = form.save()
            messages.success(request, f'Assunto {assunto.assunto} alterado com sucesso!')
            return redirect("provas:atualizarAssunto", id=assunto.id)

        return render(request, f'{BASE_PATH}cadastrarAssunto.html', context=context)
    context={
        'listar': {
            'url': reverse('provas:assuntos'),
            'nome': 'Assuntos',
        },
        'form': AssuntoForm(instance=assunto),
        'from_action': form_action,
    }
    return render(request, f'{BASE_PATH}cadastrarAssunto.html', context=context)

def apagarAssunto(request: HttpRequest, id):
    assunto = get_object_or_404(Assunto, id=id, ativo=True)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        assunto.delete()
        return redirect('provas:assuntos')

    context={
        'listar': {
            'url': reverse('provas:assuntos'),
            'nome': 'Assuntos',
        },
        'assunto': assunto,
        'confirmation': confirmation,
    }
    return render(request, f'{BASE_PATH}consultarAssunto.html', context=context)

provasOrais/views/home.py
from django.shortcuts import render

# Create your views here.
def home(request):
    full_url = f"{request.scheme}://{request.get_host()}{request.get_full_path()}"
    context={}
    return render(request, 'provasOrais/templates/home.html', context=context)

provasOrais/views/usuario.py
from django.shortcuts import render
from provasOrais.forms import UsuarioForm
from django.http import HttpRequest

BASE_PATH = 'provasOrais/templates/'

def cadastrarUsuario(request: HttpRequest):
    form = UsuarioForm()

    if request.method == "POST":
        form = UsuarioForm(request.POST)

        if form.is_valid():
            form.save()


    context = {
        'form': form
    }

    return render(request, f'{BASE_PATH}cadastrarUsuario.html', context=context)

pages/provasOrais/templates/atualizarProva.html
{% extends "global/templates/base.html" %}

{% block main %}
    <form action="{{form_action}}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if aluno %}
            <input type="hidden" name="aluno" value="{{aluno}}">
        {% endif %}


        {% if form %}
            {% for questao in form %}
                <label for="id_questao">Questão</label>
                <select name="questao" id="id_questao" style="display: none" required>
                    <option value="{{questao.questao.id}}" selected></option>
                </select>
                <textarea cols="40" rows="5" disabled>{{questao.questao}}</textarea>
                {% if questao.help_text %}
                    <p class="help_text">{{questao.help_text}}</p>
                {% endif %}
                <label for="{{questao.resposta.id_for_label}}">{{questao.resposta.label}}</label>
                {{questao.resposta}}
                {% if questao.resposta.help_text %}
                    <p class="help_text">{{questao.resposta.help_text}}</p>
                {% endif %}
                <label for="{{questao.nota.id_for_label}}">{{questao.nota.label}}</label>
                {{questao.nota}}
                {% if questao.nota.help_text %}
                    <p class="help_text">{{questao.nota.help_text}}</p>
                {% endif %}

                {% if questao.non_field_errors %}
                    <div>
                        {{questao.non_field_errors}}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if form.non_field_errors %}
            <div>
                {{form.non_field_errors}}
            </div>
        {% endif %}
        <input type="submit" value="Enviar">
    </form>
{% endblock main %}

pages/provasOrais/templates/cadastrarPergunta.html
{% extends "global/templates/base.html" %}

{% block main %}
    <form action="{{form_action}}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="{{form.aluno.id_for_label}}">{{form.aluno.label}}</label>
        {{form.aluno}}
        {% if form.aluno.help_text %}
            <p class="help_text">{{form.aluno.help_text}}</p>
        {% endif %}
        {% for questao in questoes %}

        <label for="id_questao">Questão</label>
        <select name="questao" id="id_questao" style="display: none" required>
            <option value="{{questao.id}}" selected></option>
        </select>
        <textarea cols="40" rows="3" disabled>{{questao}}</textarea>
        {% if questao.help_text %}
            <p class="help_text">{{questao.help_text}}</p>
        {% endif %}

        <label for="{{form.resposta.id_for_label}}">{{form.resposta.label}}</label>
        {{form.resposta}}
        {% if form.resposta.help_text %}
            <p class="help_text">{{form.resposta.help_text}}</p>
        {% endif %}

        <label for="{{form.nota.id_for_label}}">{{form.nota.label}}</label>
        {{form.nota}}
        {% if form.nota.help_text %}
            <p class="help_text">{{form.nota.help_text}}</p>
        {% endif %}

        {% if form.non_field_errors %}
            <div>
                {{form.non_field_errors}}
            </div>
        {% endif %}
        {% endfor %}
        <input type="submit" value="Enviar">
    </form>
{% endblock main %}

pages/provasOrais/templates/cadastrarProva.html
{% extends "global/templates/base.html" %}

{% block main %}
    <form action="{{form_action}}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if not questoes %}
            {% for field in form %}
                <label for="{{field.id_for_label}}">{{field.label}}</label>
                {{field}}
                {% if field.help_text %}
                    <p class="help_text">{{field.help_text}}</p>
                {% endif %}
                {{field.errors}}
            {% endfor %}
        {% endif %}

        {% if aluno %}
            <input type="hidden" name="aluno" value="{{aluno}}">
        {% endif %}

        {% if questoes %}
            {% for questao in questoes %}
                <label for="id_questao">Questão</label>
                <select name="questao" id="id_questao" style="display: none" required>
                    <option value="{{questao.id}}" selected></option>
                </select>
                <textarea cols="40" rows="5" disabled>{{questao}}</textarea>
                {% if questao.help_text %}
                    <p class="help_text">{{questao.help_text}}</p>
                {% endif %}
                <label for="{{form.resposta.id_for_label}}">{{form.resposta.label}}</label>
                {{form.resposta}}
                {% if form.resposta.help_text %}
                    <p class="help_text">{{form.resposta.help_text}}</p>
                {% endif %}
                <label for="{{form.nota.id_for_label}}">{{form.nota.label}}</label>
                {{form.nota}}
                {% if form.nota.help_text %}
                    <p class="help_text">{{form.nota.help_text}}</p>
                {% endif %}

                {% if form.non_field_errors %}
                    <div>
                        {{form.non_field_errors}}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if form.non_field_errors %}
            <div>
                {{form.non_field_errors}}
            </div>
        {% endif %}
        <input type="submit" value="Enviar">
    </form>
{% endblock main %}

pages/provasOrais/templates/home.html
{% extends "global/templates/base.html" %}
{% load static %}
{% block pageStyle %}{% static "styles/home.css" %}{% endblock pageStyle %}
{% block pageTitle %}Página inicial{% endblock pageTitle %}

{% block main %}
<section class="main">
    <div class="card-menu"><a href="{% url "provas:disciplinas" %}">Disciplinas</a></div>
    <div class="card-menu"><a href="{% url "provas:assuntos" %}">Assuntos</a></div>
    <div class="card-menu"><a href="{% url "provas:questoes" %}">Questões</a></div>
    <div class="card-menu"><a href="{% url "provas:turmas" %}">Turmas</a></div>
    <div class="card-menu"><a href="{% url "provas:alunos" %}">Alunos</a></div>
    <div class="card-menu"><a href="{% url "provas:provas" %}">Provas aplicadas</a></div>
</section>
{% endblock main %}

pages/provasOrais/templates/listarAssuntos.html
{% extends "global/templates/base.html" %}

{% block pageTitle %}Assuntos{% endblock pageTitle %}

{% block main %}
    {% include "provasOrais/partials/novoActionMenu.html" %}
    <div class="table table-title">
        <div class='table-title table-item'>ID</div>
        <div class='table-title table-item'>Assunto</div>
        <div class='table-title table-item'>Disciplina</div>
    </div>
    <div class="table-container">
        {% for assunto in assuntos %}
            <a href="{% url "provas:assunto" assunto.id %}">
                <div class='table table-line'>
                    <div class='table-item'>{{assunto.id}}</div>
                    <div class='table-item'>{{assunto.assunto}}</div>
                    <div class='table-item'>{{assunto.disciplina}}</div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock main %}

pages/provasOrais/templates/listarDisciplinas.html
{% extends "global/templates/base.html" %}

{% block pageTitle %}Disciplinas{% endblock pageTitle %}

{% block main %}
    {% include "provasOrais/partials/novoActionMenu.html" %}
    {% comment %} <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Disciplina</th>
            </tr>
        </thead>
        <tbody>
            {% for disciplina in disciplinas %}
                <tr>
                    <td><a href="{% url "provas:disciplina" disciplina.id %}">{{disciplina.id}}</a></td>
                    <td>{{disciplina.disciplina}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table> {% endcomment %}
    <div class="table table-title">
        <div class='table-title table-item'>ID</div>
        <div class='table-title table-item'>Disciplina</div>
    </div>
    <div class="table-container">
        {% for disciplina in disciplinas %}
            <a href="{% url "provas:disciplina" disciplina.id %}">
                <div class='table table-line'>
                    <div class='table-item'>{{disciplina.id}}</div>
                    <div class='table-item'>{{disciplina.disciplina}}</div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock main %}

pages/provasOrais/templates/listarPerguntas.html
{% extends "global/templates/base.html" %}

{% block pageTitle %}Provas{% endblock pageTitle %}

{% block main %}
    <nav>
        <li><a href={% url "provas:receberAssunto" %}><i class="fa-solid fa-plus"></i> Novo</a></li>
    </nav>
    {% comment %} <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Aluno</th>
                <th>Questão</th>
                <th>Nota</th>
            </tr>
        </thead>
        <tbody>
            {% for pergunta in perguntas %}
                <tr>
                    <td><a href="{% url "provas:pergunta" pergunta.id %}">{{pergunta.id}}</a></td>
                    <td>{{pergunta.prova.aluno}}</td>
                    <td>{{pergunta.questao.assunto}}</td>
                    <td>{{pergunta.nota}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table> {% endcomment %}
    <div class="table table-title">
        <div class='table-title table-item'>ID</div>
        <div class='table-title table-item'>Aluno</div>
        <div class='table-title table-item'>Assunto</div>
        <div class='table-title table-item'>Nota</div>
    </div>
    <div class="table-container">
        {% for pergunta in perguntas %}
            <a href="{% url "provas:pergunta" pergunta.id %}">
                <div class='table table-line'>
                    <div class='table-item'>{{pergunta.id}}</div>
                    <div class='table-item'>{{pergunta.prova.aluno}}</div>
                    <div class='table-item'>{{pergunta.questao.assunto}}</div>
                    <div class="table-item">{{pergunta.nota}}</div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock main %}

pages/provasOrais/templates/listarProvas.html
{% extends "global/templates/base.html" %}

{% block pageTitle %}Provas{% endblock pageTitle %}

{% block main %}
    {% include "provasOrais/partials/novoActionMenu.html" %}
    <div class="table table-title">
        <div class='table-title table-item'>ID</div>
        <div class='table-title table-item'>Assunto</div>
        <div class='table-title table-item'>Disciplina</div>
    </div>
    <div class="table-container">
        {% for prova in provas %}
            <a href="{% url "provas:prova" prova.id %}">
                <div class='table table-line'>
                    <div class='table-item'>{{prova.id}}</div>
                    <div class="table-item">{{prova.aluno}}</div>
                    <div class="table-item">{{prova.nota}}</div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock main %}